wocky-client integration using git subtree (#2330)
* AddressData fix and other improvements

* remove console logs

* temporary disable

* fixed follow/unfollow

* new message send/upload API and other improvements

* message trim before sending

* make isNew settable

* bot posts load fix

* custom snapshoting and other improvements

* fix typeerror

* improve custom snapshots

* Factory interface

* fxies

* fix typo

* improve reference management, other fixes

* sessionCount, push and other fixes/improvements

* OwnProfile fix

* improve tests, refactor Wocky

* complete refactoring, other improvements

* fix logs

* fix unit test

* for rn-chat #1807. avoid welcome message for existing users

* fixes issues

* fix errors

* fix eslint

* fix unit tests

* fix unit tests

* allow "force" loading of paginable lists

* fixes and improvements

* change force param

* fixes and improvements

* remove console.log

* set finished when no results (temp solution for homestream)

* export EventList

* login and HS update improvement

* fix unit tests

* remember to build after each change ;)

* for https://github.com/hippware/rn-chat/issues/1834

* prepare for offline work, small fixes

* update "Saved bots"

* missed profile loading for HS

* fix null data

* tsc'd changes

* small adjustments

* clearCache method

* fix test

* watchmanconfig for wml

* update typescript

* make isNew settable/persistable

* processing HS delete items, other improvements

* process delete HS items, other improvements

* remove logs

* hot-fix: update version at the beginning of onNotification

* added geofence prop

* added setGeofence method

* add geofence stuff

* adjust geofence unsubscribe

* fix unsubscribe

* for https://github.com/hippware/rn-chat/issues/1960

* fix typescript version

* for #1946

* for rn-chat/#1946

* for hippware/rn-chat#1962

* speculative fix for hippware/rn-chat#1980, hippware/rn-chat#1982

* fix unit tests, add more

* added timeout promise

* process bot geofence boolean strings

* WIP: geofence guest list + tests

* geofence changes

* rework geofence

* more improvements

* temporary disable visitors API

* for #1897 and better bot loading

* add RSM for visitors

* fixes for possible logout stuck

* geofence bot shares

* support geofence bot shares

* for #2027

* fix test line in package.json

* graphql test

* fix lint errors

* huge refactoring for new graphql transport

* restore node-fetch

* for #2035, #1903

* export types, fix compile errors

* graphql and typescript fixes

* paging refactoring, more graphql

* export more types

* types

* simplify types to avoid compilation errors for rn-chat (T is undefined)

* fix unit test

* for https://github.com/hippware/rn-chat/issues/2030

* improve typings

* for https://github.com/hippware/rn-chat/issues/2066

* rework hippware/rn-chat#2066

* for hippware/rn-chat#2082, hippware/rn-chat#2034

* add websocket dep

* improve typing

* close socket for disconnect

* WIP: first subscription draft

* fix unit tests

* fix unit tests

* improve types

* fix graphql test (?)

* Addresses hippware/rn-chat#2046 with unit tests

* added aggregator counts

* resolve conflicts

* add todo for remove()

* location snapshot type

* bot list retrieval, updated mutations

* new format for bot live visitor subscription

* fix unit test

* hot-fix: fix graphql crashes

* hot-fix: pagination fix for graphql cursors

* hot-fix: fix bugsnag crashes

* improve visitor unit test

* hot-fix: temporary disable retrieval of suscribed bots via graphql

* share location via graphql

* fix unit tests

* disable logs

* improve the code for 'active geofence bots' header UI

* S3 URL support

* convert images for profiles

* update zen-observable to show more meangful errors

* fix unit tests

* trying to fix unit test

* more fixes

* annotate mobx actions in Transport classes

* improve bot live updates

* trying to fix unit tests

* more improvements

* fix bot visitor retrieval and subscription

* fix passing visitor id

* fix unit tests

* fix unit tests

* remove logging

* sorter order of bots

* Add changelog (stub).

* make latest visitor always on the top

* EXPERIMENT: connection

* Update CHANGELOG.md

* more improvements

* add action annotation

* disable websocket reconnect

* temporary disable graphql subscription tests

* remove console.log

* initial implementation

* add getLocationsVisited

* Update CHANGELOG.md

* sythnetic test to check ability graphql to connect/disconnect several times

* less attempts to decrease test time

* simplify logic (because internal reconnect is disabled)

* update circleci image

* upgrade to latest nodejs and yarn

* increase timeout to work with EDGE network

* Fix finished flag (hippware/rn-chat#2213)

* Update CHANGELOG.md

* Update CHANGELOG.md

* enable subscription disabled tests

* Update CHANGELOG.md

* expose `resource` on wocky.transport

* Update CHANGELOG.md

* graphql: currentUser for loading own profile

* currentUser on loadBots query

* created new test to demonstrate the issue that must be fixed

* don't use amazon urls as file uri

* typings

* separate public and private fields on loadProfile

* reworked code, better unit tests

* merge master

* active bot graphql implementation

* persistence for geofenceBots

* fixes unit tests and subscribe/unsubscribe

* clear cache during logout

* use refresh to clear activeBots

* revert to client-side ordering

* attempt to fix unit test

* fix unit test

* check `connected` on loadProfile

* WIP: IProfilePartial contract

* hot-fix: attempt to fix conversion error hippware/rn-chat#2285

* Update CHANGELOG.md

* temporary disable some part of unit tests to pass under graphql

* null user profile handling

* fix addressData exception and tests

* update profile via graphql

* GQL: loadBotSubscribers

* extract graphql logic to separate function; visitors, guests

* correct logic for excluding currentUser

* correct count for !includeCurrent

* Update CHANGELOG.md

* remove bot from geofenceBot

* hot-fix: use correct force param

* Update CHANGELOG.md

* Tslint upgrade and code improvements

* fix errors

* Update CHANGELOG.md

* reformat code, fix unit tests

* remove wocky-client

* remove generated lib

* point to main index

* remove unused locals and prettify